import type { Metadata } from "next";
import "./globals.css";
import QueryProviderWrapper from "@/components/provider/query.provider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`w-full h-full`}>
				<QueryProviderWrapper>
					<Navbar />
					<div className="w-11/12 h-full mx-auto max-w-screen-2xl">{children}</div>
					<Toaster />
				</QueryProviderWrapper>
			</body>
		</html>
	);
}
